package csmc.hospital.notifier.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF00478d)
val OnPrimary = Color(0xFFffffff)
val PrimaryContainer = Color(0xFF005eb8)
val OnPrimaryContainer = Color(0xFFc8daff)
val Secondary = Color(0xFF006970)
val OnSecondary = Color(0xFFffffff)
val SecondaryContainer = Color(0xFF7af1fc)
val OnSecondaryContainer = Color(0xFF006e75)
val Tertiary = Color(0xFF43484c)
val OnTertiary = Color(0xFFffffff)
val TertiaryContainer = Color(0xFF5b6063)
val OnTertiaryContainer = Color(0xFFd6dade)
val Error = Color(0xFFba1a1a)
val OnError = Color(0xFFffffff)
val ErrorContainer = Color(0xFFffdad6)
val OnErrorContainer = Color(0xFF93000a)
val Background = Color(0xFFf8f9ff)
val OnBackground = Color(0xFF0b1c30)
val Surface = Color(0xFFf8f9ff)
val OnSurface = Color(0xFF0b1c30)
val SurfaceVariant = Color(0xFFd3e4fe)
val OnSurfaceVariant = Color(0xFF424752)
val Outline = Color(0xFF727783)
val OutlineVariant = Color(0xFFc2c6d4)

val PrimaryFixed = Color(0xFFd6e3ff)
val PrimaryFixedDim = Color(0xFFa9c7ff)
val OnPrimaryFixed = Color(0xFF001b3d)
val OnPrimaryFixedVariant = Color(0xFF00468c)

val SurfaceContainerLowest = Color(0xFFffffff)
val SurfaceContainerLow = Color(0xFFeff4ff)
val SurfaceContainer = Color(0xFFe5eeff)
val SurfaceContainerHigh = Color(0xFFdce9ff)
val SurfaceContainerHighest = Color(0xFFd3e4fe)
